  ---
  - hosts: beacons
    gather_facts: yes
    remoute_user: {{user}}

    tasks:
      - name: Update
        apt:
          update_cache: yes

        - name: Check if packages are installed #for using pip module on management host
        shell: apt list --installed | grep {{ item }}
        with_items:
          {{ pkgs }}
        register: installed_pkgs
        failed_when: no
        - name: Debug found pkgs
          debug:
            msg: {{ installed_pkgs.stdout_lines }}
        - name: Install absent packages
        with_items:
          {{ pkgs }}
        when: {{ item }} not in installed_pkgs.stdout
        
      - name: Check if modules are installed via pip #for using pip module on management host
        shell: pip3 list | grep {{ item }}
        with_items:
          {{ modules }}
        register: installed_modules
        failed_when: no
      - name: Debug found modules
        debug:
           msg: {{ installed_modules.stdout_lines }}

      # Install absent modules
      - pip:
        name: {{ modules }}  
        with_items:
          {{ modules }}
        when: {{ item }} not in installed_modules.stdout

      
      
          
