---
  #- name: Update
    #apt:
      #update_cache: yes
      #cache_valid_time: 86400
    #become: yes
    #become_method: sudo

  - name: Install packages
    apt: 
      pkg: "{{ pkgs }}"
      state: present

  # Install absent modules
  - pip:
      name:
        - setuptools
        - evdev
        - kafka-python
        - pybluez
        - mcpi
        - kazoo
        #- bitstring
      state: latest
     
  - name: Check is it a new scanner
    stat:
      path: /iscan3
    register: stat_result
        
  - name: Create directory for iBeacon Scanner
    file:
      path: /iscan3
      state: directory    
        
  - git:
      repo: "{{ iscan3_repository_url }}"
      dest: /iscan3
      force: yes

  - name: Debug fetch  
    debug:
      msg: "Repository  was cloned"
      
  - name: Move service file to the proper directory
    shell: mv iscan3.service /etc/systemd/system
    args:
      chdir: /iscan3/
       
  - name: Add logging
    shell: cat iscan3.log >> /etc/logrotate.d/rsyslog
    args:
      chdir: /iscan3/
     
  - name: start iscan3 service
    systemd:
      state: started
      name: iscan3
      enabled: yes
      daemon_reload: yes
         
  - name: Check if iscan 3 is running
    shell: systemctl status iscan3
    register: iscan3_status
    
  - name: Print service state  
    debug:
      msg: "{{ iscan3_status }}"
         
  - name: Start logging
    shell: logrotate /etc/logrotate.d/rsyslog
    
  - name: Check log   
    debug:
      msg: "Log created"

#- name: reboot if scanner just configured
#  reboot:
#   msg: "Reboot initiated by Ansible"
#   when: dir_iscan3.exists == false

        
